apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-spiffe-helper-config
  namespace: spiffe-helper-webhook
data:
  helper.conf: |
    agent_address = "/run/spire/agent-sockets/socket"
    cert_dir = "/run/spiffe/certs"
    svid_file_name = "svid.pem"
    svid_key_file_name = "svid_key.pem"
    svid_bundle_file_name = "svid_bundle.pem"