apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spiffe-helper-webhook

resources:
  - deployment.yaml
  - service.yaml
  - webhook.yaml
  - rbac.yaml
  - cluster-spiffe-ids.yaml
  - configmaps.yaml

images:
  - name: spiffe-helper-webhook
    newName: fengyu225/spiffe-helper-webhook
    newTag: v0.0.1