apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-helper-webhook
  namespace: spiffe-helper-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spiffe-helper-webhook
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spiffe-helper-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spiffe-helper-webhook
subjects:
  - kind: ServiceAccount
    name: spiffe-helper-webhook
    namespace: spiffe-helper-webhook